services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: temppass
      DB_NAME: loginlogsdb

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: temppass
      MYSQL_DATABASE: loginlogsdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
